In [4]:
#command to download numpy module 
# !python -m pip install numpy

In [7]:
!python -m pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy as np

In [9]:
#NumPy Datatype
### Numpy.nd.array

In [18]:
a = np.array([3,8,2,67,45])
a

def show_array(arr):
    print("Array",arr,sep = '\n')
    print("Shape",arr.shape)
    print("Type",type(arr))
    print("Size",arr.size)
    print("DataType",arr.dtype)
    print("Length",len(arr))
    print("Dimension",arr.ndim)

    

In [19]:
print(type(a))
print(a.shape)
print(a.size)
print(a.dtype)
#additionaly can check length 
print(len(a))

<class 'numpy.ndarray'>
(5,)
5
int32
5


In [22]:
#2D Array in numpy

# 10 11 13 14
# 45 22 9  2
# 6  5  1  8

b = np.array ([[10,11,13,14],[45,22,9,2],[6,5,1,8]])
show_array(b)


Array
[[10 11 13 14]
 [45 22  9  2]
 [ 6  5  1  8]]
Shape (3, 4)
Type <class 'numpy.ndarray'>
Size 12
DataType int32
Length 3


In [23]:
#ARRAY OPERATIONS

# 1. Item Accessing: Subsripting , Slicing
# 2. Item Assignment
# 3. Item Insertion
# 4. Item Deletion
# 5. Arthematic Operations

In [24]:
#3D Array in numpy

             # 100 110 130 140
             # 145 122 19  12
             # 16  15  11  18

# 10 11 13 14
# 45 22 9  2
# 6  5  1  8

c = np.array ([[[10,110],[11,110],[13,130],[14,140]],
               [[45,145],[22,122],[9,19],[2,12]],
               [[6,16],[5,15],[1,11],[8,18]]])
show_array(c)


Array
[[[ 10 110]
  [ 11 110]
  [ 13 130]
  [ 14 140]]

 [[ 45 145]
  [ 22 122]
  [  9  19]
  [  2  12]]

 [[  6  16]
  [  5  15]
  [  1  11]
  [  8  18]]]
Shape (3, 4, 2)
Type <class 'numpy.ndarray'>
Size 24
DataType int32
Length 3


In [26]:
b = np.array ([[10,11,13,14],[45,22,9,2],[6,5,1,8]])
b

array([[10, 11, 13, 14],
       [45, 22,  9,  2],
       [ 6,  5,  1,  8]])

In [36]:
#1. Item Accessing
#b[0][0]
#b[1][1:]
# now want to access random numbers from different rows then need to use subscripting (not normal indexing, use subsrcipt for indexing and slicing)
#subscripting [1st,2nd,3rd.....nth dim]
#subscripting slicing [1st:1st end:stepsize,,2nd,3rd.....nth dim]
b[0,0]
b[1,-3:]
b[:,-2]

array([13,  9,  1])

In [37]:
b[:,-2].shape

(3,)

In [43]:
#want this in column form then just write slice in that way
b[:,-2:-1]

array([[13],
       [ 9],
       [ 1]])

In [44]:
print(b[:,-2:-1].shape)     

(3, 1)


In [57]:
b[-1][0:]

array([6, 5, 1, 8])

In [59]:
b[2][0:].shape

(4,)

In [66]:
c[0,1,0],c[1,1,0],c[2,1,0]

(11, 22, 5)

In [68]:
#Ans for sir questions
print(b[-1:,:])
print("\n")
print(c[:1,:2,:])
print("\n")
print(c[:,1:2,:1])
print("\n")
print(c[:-2,-1:,:1])
print("\n")
print(c[:2,-2:,:])

[[6 5 1 8]]


[[[ 10 110]
  [ 11 110]]]


[[[11]]

 [[22]]

 [[ 5]]]


[[[14]]]


[[[ 13 130]
  [ 14 140]]

 [[  9  19]
  [  2  12]]]


In [71]:
# Item Assignment in numpy
b[1,2] = 90
b

array([[10, 11, 13, 14],
       [45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [72]:
#Item Insertion
#based on the shape of array

# 1D Array insertion
np.append(a,80)

array([ 3,  8,  2, 67, 45, 80])

In [73]:
#but not updated in a.

array([ 3,  8,  2, 67, 45])

In [74]:
#So
a = np.append(a,80)
a

array([ 3,  8,  2, 67, 45, 80])

In [76]:
# 2D Array Insertion
# can't do straightforwardly, have to give axis too.
np.append(b,[[1],[23],[8000]],axis =1) #axis = 0 means row and axis =1 means column and also need to match the shape of data accordingly to axis.
 



array([[  10,   11,   13,   14,    1],
       [  45,   22,   90,    2,   23],
       [   6,    5,    1,    8, 8000]])

In [78]:
np.append(b,[[1,23,8000,8]],axis =0)

array([[  10,   11,   13,   14],
       [  45,   22,   90,    2],
       [   6,    5,    1,    8],
       [   1,   23, 8000,    8]])

In [86]:
#Item Deletion
b1 = b.copy()
print(b1)
print("\nAfer Deletion")
np.delete(b1,0,axis =0)

[[10 11 13 14]
 [45 22 90  2]
 [ 6  5  1  8]]

Afer Deletion


array([[45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [89]:
#Arthematic Operations
#e.g
print(a*2)
print("\n")
print(b1*2)

[  6  16   4 134  90 160]


[[ 20  22  26  28]
 [ 90  44 180   4]
 [ 12  10   2  16]]


In [90]:
print(b1-2)

[[ 8  9 11 12]
 [43 20 88  0]
 [ 4  3 -1  6]]


In [99]:
#Array Manipulation 

#arr.reshape()
#e.g
#b1.reshape(2,6,1,1)

#arr.astype(type)
#e.g b1.astype('uint16)
#numpy gives float64 by default.


#More functions to create array
#1. np.array()
#2. np.arrange()        -> array version of range func, also allows float
#3. np.linspace()       -> start,end, no. of items
#4. np.ones()           -> generate all the values as '1'
#4. np.zeros()          -> generate all the values as '0'
#5. np.random.random()  -> generate all the values as random
#6. np.random.randint() -> generate all the values as random integers.

In [101]:
#to form a array of elements as 5.
np.ones((3,4),dtype = 'int')*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])